# AppVeyor configuration for EPICS Base

# Ralph Lange <ralph.lange@gmx.de>
# Copyright (c) 2016-2017 ITER Organization

# Version format
version: base-{branch}-{build}

#---------------------------------#
#       repository cloning        #
#---------------------------------#

# Called at very beginning, before repo cloning
init:
  # Set autocrlf to make batch files work
  - git config --global core.autocrlf true
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# Set clone depth (do not fetch complete history)
clone_depth: 50

# Skipping commits affecting only specific files
skip_commits:
  files:
    - 'documentation/*'
    - 'templates/*'
    - '**/*.html'
    - '**/*.md'

#---------------------------------#
#   build matrix configuration    #
#---------------------------------#

# Build Configurations: dll/static, regular/debug
configuration:
  - dynamic-debug
  - static-debug
#  - dynamic
#  - static

# Environment variables: compiler toolchain
environment:
  matrix:
  - TOOLCHAIN: 11.0
  - TOOLCHAIN: 12.0
  - TOOLCHAIN: 10.0
  - TOOLCHAIN: 14.0
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    TOOLCHAIN: 2017
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    TOOLCHAIN: 2019
  - TOOLCHAIN: cygwin
  - TOOLCHAIN: mingw
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

# Platform: architecture
platform:
  - x86
  - x64

# Matrix configuration: allow specific failing jobs
matrix:
  exclude:
  # VS Express installs don't have the 64 bit compiler
  - platform: x64
    TOOLCHAIN: 10.0
  # Cygwin static-debug has compiler problems
  - configuration: static-debug
    TOOLCHAIN: cygwin
  # Cygwin x86 install is currently (08/2019) broken (libncursesw-devel fails)
  - platform: x86
    TOOLCHAIN: cygwin


#---------------------------------#
#     building & testing          #
#---------------------------------#

install:
  - cmd: git submodule update --init --recursive
  - cmd: .ci/appveyor-prepare.bat

build_script:
  - cmd: .ci/appveyor-make.bat

test_script:
  - cmd: .ci/appveyor-make.bat runtests


#---------------------------------#
#         debugging               #
#---------------------------------#
## if you want to connect by remote desktop to a failed build, uncomment these lines
## note that you will need to connect within the usual build timeout limit (60 minutes)
on_failure:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


#---------------------------------#
#         notifications           #
#---------------------------------#

#notifications:
#
#  - provider: Email
#    to:
#      - core-talk@aps.anl.gov
#    on_build_success: false
#
#  - provider: GitHubPullRequest
